language: node_js

node_js:
  - '9'

matrix:
  include:
  - os: osx

cache:
  yarn: true

notifications:
  email: false

script:
  - npm i
  - npm run package

deploy:
  provider: releases
  api_key: $ENCRYPTED_GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true